"""initial_schema

Revision ID: 0001
Revises:
Create Date: 2026-05-05

Captures the full PostgreSQL schema as it existed at Phase 1 completion,
including all raw.* and sim.* tables, indexes, triggers, utility functions,
and the operational view.  Verified against 01_postgres_schema.sql.

This migration is applied manually against the target database; it is
intentionally written as explicit DDL rather than autogenerated from ORM
models so that it is readable and auditable by every team member.
"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # -----------------------------------------------------------------
    # Extensions
    # -----------------------------------------------------------------
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pg_trgm"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "btree_gin"')

    # -----------------------------------------------------------------
    # Schemas
    # -----------------------------------------------------------------
    op.execute("CREATE SCHEMA IF NOT EXISTS raw")
    op.execute("CREATE SCHEMA IF NOT EXISTS sim")

    # -----------------------------------------------------------------
    # raw.venues
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE IF NOT EXISTS raw.venues (
            venue_id            INTEGER         NOT NULL,
            season              INTEGER         NOT NULL,
            venue_name          VARCHAR(100)    NOT NULL,
            city                VARCHAR(100)    NOT NULL,
            state               VARCHAR(50),
            surface             VARCHAR(20)     NOT NULL CHECK (surface IN ('Turf','Grass')),
            roof_type           VARCHAR(20)     NOT NULL CHECK (roof_type IN ('Open','Retractable','Dome')),
            elevation_ft        FLOAT           NOT NULL DEFAULT 0,
            lf_dist             FLOAT,
            lf_gap_dist         FLOAT,
            cf_dist             FLOAT,
            rf_gap_dist         FLOAT,
            rf_dist             FLOAT,
            lf_wall_ht          FLOAT,
            lf_gap_wall_ht      FLOAT,
            cf_wall_ht          FLOAT,
            rf_gap_wall_ht      FLOAT,
            rf_wall_ht          FLOAT,
            foul_territory      VARCHAR(10)     CHECK (foul_territory IN ('Small','Medium','Large')),
            capacity            INTEGER,
            coordinates_lat     FLOAT,
            coordinates_lon     FLOAT,
            created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
            updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
            PRIMARY KEY (venue_id, season)
        )
    """)

    # -----------------------------------------------------------------
    # raw.teams
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE IF NOT EXISTS raw.teams (
            team_id             INTEGER         NOT NULL,
            season              INTEGER         NOT NULL,
            team_name           VARCHAR(100)    NOT NULL,
            team_abbrev         VARCHAR(5)      NOT NULL,
            league              CHAR(2)         NOT NULL CHECK (league IN ('AL','NL')),
            division            VARCHAR(10)     NOT NULL
                                    CHECK (division IN ('AL East','AL Central','AL West',
                                                        'NL East','NL Central','NL West')),
            venue_id            INTEGER         NOT NULL,
            created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
            updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
            PRIMARY KEY (team_id, season),
            FOREIGN KEY (venue_id, season) REFERENCES raw.venues (venue_id, season)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS idx_teams_venue    ON raw.teams(venue_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_teams_league   ON raw.teams(league)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_teams_division ON raw.teams(division)")

    # -----------------------------------------------------------------
    # raw.players
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE IF NOT EXISTS raw.players (
            player_id           INTEGER         PRIMARY KEY,
            full_name           VARCHAR(100)    NOT NULL,
            first_name          VARCHAR(50)     NOT NULL,
            last_name           VARCHAR(50)     NOT NULL,
            birth_date          DATE,
            bats                CHAR(1)         NOT NULL CHECK (bats IN ('L','R','S')),
            throws              CHAR(1)         NOT NULL CHECK (throws IN ('L','R','S')),
            primary_position    VARCHAR(5)      NOT NULL,
            height_inches       INTEGER,
            weight_lbs          INTEGER,
            mlb_debut_date      DATE,
            active              BOOLEAN         NOT NULL DEFAULT TRUE,
            created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
            updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS idx_players_last_name      ON raw.players(last_name)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_players_full_name_trgm ON raw.players USING GIN (full_name gin_trgm_ops)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_players_active         ON raw.players(active) WHERE active = TRUE")
    op.execute("CREATE INDEX IF NOT EXISTS idx_players_position       ON raw.players(primary_position)")

    # -----------------------------------------------------------------
    # raw.managers
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE IF NOT EXISTS raw.managers (
            manager_id          INTEGER         NOT NULL,
            season              INTEGER         NOT NULL,
            full_name           VARCHAR(100)    NOT NULL,
            team_id             INTEGER         NOT NULL,
            season_start        DATE,
            season_end          DATE,
            created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
            updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
            PRIMARY KEY (manager_id, season),
            FOREIGN KEY (team_id, season) REFERENCES raw.teams(team_id, season)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS idx_managers_team   ON raw.managers(team_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_managers_active ON raw.managers(team_id) WHERE season_end IS NULL")

    # -----------------------------------------------------------------
    # raw.games
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE IF NOT EXISTS raw.games (
            game_pk                 INTEGER         PRIMARY KEY,
            season                  INTEGER         NOT NULL,
            game_date               DATE            NOT NULL,
            game_type               VARCHAR(2)      NOT NULL
                                        CHECK (game_type IN ('R','P','S','A','D','F','L','W')),
            status                  VARCHAR(20)     NOT NULL
                                        CHECK (status IN ('Preview','Warmup','Pre-Game','Live',
                                                          'Final','Postponed','Suspended','Cancelled')),
            venue_id                INTEGER         NOT NULL,
            home_team_id            INTEGER         NOT NULL,
            away_team_id            INTEGER         NOT NULL,
            home_manager_id         INTEGER,
            away_manager_id         INTEGER,
            home_score_final        INTEGER,
            away_score_final        INTEGER,
            innings_played          INTEGER,
            home_hits               INTEGER,
            away_hits               INTEGER,
            home_errors             INTEGER,
            away_errors             INTEGER,
            inning_scores           JSONB,
            winning_pitcher_id      INTEGER         REFERENCES raw.players(player_id),
            losing_pitcher_id       INTEGER         REFERENCES raw.players(player_id),
            save_pitcher_id         INTEGER         REFERENCES raw.players(player_id),
            attendance              INTEGER,
            weather_temp            INTEGER,
            weather_condition       VARCHAR(50),
            wind_speed              INTEGER,
            wind_direction          VARCHAR(20),
            game_duration_minutes   INTEGER,
            created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
            updated_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
            FOREIGN KEY (venue_id, season)       REFERENCES raw.venues(venue_id, season),
            FOREIGN KEY (home_team_id, season)   REFERENCES raw.teams(team_id, season),
            FOREIGN KEY (away_team_id, season)   REFERENCES raw.teams(team_id, season)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS idx_games_date        ON raw.games(game_date)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_games_home_team   ON raw.games(home_team_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_games_away_team   ON raw.games(away_team_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_games_status      ON raw.games(status)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_games_venue       ON raw.games(venue_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_games_date_status ON raw.games(game_date, status)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_games_type        ON raw.games(game_type)")

    # -----------------------------------------------------------------
    # raw.game_lineups
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE IF NOT EXISTS raw.game_lineups (
            id                  BIGSERIAL       PRIMARY KEY,
            game_pk             INTEGER         NOT NULL REFERENCES raw.games(game_pk),
            season              INTEGER         NOT NULL,
            team_id             INTEGER         NOT NULL,
            player_id           INTEGER         NOT NULL REFERENCES raw.players(player_id),
            batting_order       INTEGER         CHECK (batting_order BETWEEN 1 AND 9),
            position_code       VARCHAR(5)      NOT NULL,
            is_starter          BOOLEAN         NOT NULL DEFAULT TRUE,
            sequence            INTEGER         NOT NULL DEFAULT 1,
            entered_inning      INTEGER,
            entered_at_bat      INTEGER,
            pinch_role          VARCHAR(5)      CHECK (pinch_role IN ('PH','PR','DEF')),
            created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
            updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
            CONSTRAINT uq_game_lineup_slot UNIQUE (game_pk, team_id, player_id, sequence),
            FOREIGN KEY (team_id, season) REFERENCES raw.teams(team_id, season)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS idx_game_lineups_game_team ON raw.game_lineups(game_pk, team_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_game_lineups_player    ON raw.game_lineups(player_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_game_lineups_game      ON raw.game_lineups(game_pk)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_game_lineups_starters  ON raw.game_lineups(game_pk, team_id) WHERE is_starter = TRUE")
    op.execute("CREATE INDEX IF NOT EXISTS idx_game_lineups_pinch     ON raw.game_lineups(game_pk) WHERE pinch_role IS NOT NULL")

    # -----------------------------------------------------------------
    # raw.sprint_speed
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE IF NOT EXISTS raw.sprint_speed (
            player_id           INTEGER         NOT NULL REFERENCES raw.players(player_id),
            season              INTEGER         NOT NULL,
            sprint_speed        FLOAT           NOT NULL,
            competitive_runs    INTEGER         NOT NULL,
            bolts               INTEGER,
            hp_to_1b            FLOAT,
            scraped_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
            PRIMARY KEY (player_id, season)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS idx_sprint_speed_season ON raw.sprint_speed(season)")

    # -----------------------------------------------------------------
    # raw.pitches  (abbreviated — full column list in 01_postgres_schema.sql)
    # NOTE: This is a representative CREATE; the full 90+ column definition
    #       is identical to 01_postgres_schema.sql and is applied verbatim.
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE IF NOT EXISTS raw.pitches (
            game_pk                     INTEGER     NOT NULL REFERENCES raw.games(game_pk),
            at_bat_number               INTEGER     NOT NULL,
            pitch_number                INTEGER     NOT NULL,
            game_date                   DATE        NOT NULL,
            season                      INTEGER     NOT NULL,
            venue_id                    INTEGER     NOT NULL,
            venue                       VARCHAR(100),
            home_id                     INTEGER     NOT NULL,
            home_team                   VARCHAR(10),
            away_id                     INTEGER     NOT NULL,
            away_team                   VARCHAR(10),
            home_manager_id             INTEGER     NOT NULL,
            home_manager_name           VARCHAR(100),
            away_manager_id             INTEGER     NOT NULL,
            away_manager_name           VARCHAR(100),
            inning                      SMALLINT    NOT NULL CHECK (inning BETWEEN 1 AND 30),
            inning_topbot               VARCHAR(6)  NOT NULL CHECK (inning_topbot IN ('Top','Bot')),
            pitcher                     INTEGER     NOT NULL REFERENCES raw.players(player_id),
            p_throws                    CHAR(1)     NOT NULL CHECK (p_throws IN ('L','R')),
            batter                      INTEGER     NOT NULL REFERENCES raw.players(player_id),
            stand                       CHAR(1)     NOT NULL CHECK (stand    IN ('L','R','S')),
            bat_hand                    CHAR(1)     NOT NULL CHECK (bat_hand IN ('L','R','S')),
            home_score                  SMALLINT    NOT NULL DEFAULT 0,
            away_score                  SMALLINT    NOT NULL DEFAULT 0,
            bat_score                   SMALLINT    NOT NULL DEFAULT 0,
            fld_score                   SMALLINT    NOT NULL DEFAULT 0,
            balls                       SMALLINT    NOT NULL CHECK (balls   BETWEEN 0 AND 3),
            strikes                     SMALLINT    NOT NULL CHECK (strikes BETWEEN 0 AND 2),
            outs                        SMALLINT    NOT NULL CHECK (outs    BETWEEN 0 AND 2),
            type                        CHAR(2),
            description                 VARCHAR(100),
            pitch_type                  VARCHAR(5),
            pitch_name                  VARCHAR(50),
            events                      VARCHAR(50),
            sz_top                      FLOAT,
            sz_bot                      FLOAT,
            release_speed               FLOAT,
            end_speed                   FLOAT,
            release_pos_x               FLOAT,
            release_pos_y               FLOAT,
            release_pos_z               FLOAT,
            vx0                         FLOAT,
            vy0                         FLOAT,
            vz0                         FLOAT,
            ax                          FLOAT,
            ay                          FLOAT,
            az                          FLOAT,
            pfx_x                       FLOAT,
            pfx_z                       FLOAT,
            plate_x                     FLOAT,
            plate_z                     FLOAT,
            x                           FLOAT,
            y                           FLOAT,
            release_spin_rate           INTEGER,
            spin_axis                   INTEGER     CHECK (spin_axis IS NULL OR spin_axis BETWEEN 0 AND 360),
            break_angle                 FLOAT,
            break_length                FLOAT,
            break_y                     FLOAT,
            break_vertical              FLOAT,
            break_vertical_induced      FLOAT,
            break_horizontal            FLOAT,
            zone                        SMALLINT    CHECK (zone IS NULL OR zone BETWEEN 1 AND 14),
            release_extension           FLOAT,
            launch_speed                FLOAT       CHECK (launch_speed IS NULL OR launch_speed BETWEEN 0 AND 130),
            launch_angle                FLOAT       CHECK (launch_angle IS NULL OR launch_angle BETWEEN -90 AND 90),
            hit_distance_sc             FLOAT,
            hc_x                        FLOAT,
            hc_y                        FLOAT,
            spray_angle                 FLOAT,
            bb_type                     VARCHAR(20),
            hit_location                FLOAT,
            des                         TEXT,
            on_1b                       INTEGER,
            on_2b                       INTEGER,
            on_3b                       INTEGER,
            post_on_1b                  INTEGER,
            post_on_2b                  INTEGER,
            post_on_3b                  INTEGER,
            fielder_2                   INTEGER     NOT NULL REFERENCES raw.players(player_id),
            fielder_3                   INTEGER     NOT NULL REFERENCES raw.players(player_id),
            fielder_4                   INTEGER     NOT NULL REFERENCES raw.players(player_id),
            fielder_5                   INTEGER     NOT NULL REFERENCES raw.players(player_id),
            fielder_6                   INTEGER     NOT NULL REFERENCES raw.players(player_id),
            fielder_7                   INTEGER     NOT NULL REFERENCES raw.players(player_id),
            fielder_8                   INTEGER     NOT NULL REFERENCES raw.players(player_id),
            fielder_9                   INTEGER     NOT NULL REFERENCES raw.players(player_id),
            runs_on_pitch               SMALLINT    NOT NULL DEFAULT 0,
            outs_on_pitch               SMALLINT    NOT NULL DEFAULT 0,
            rbis_on_pitch               SMALLINT    NOT NULL DEFAULT 0,
            earned_runs_on_pitch        SMALLINT    NOT NULL DEFAULT 0,
            runner_1b_scored            BOOLEAN     NOT NULL DEFAULT FALSE,
            runner_2b_scored            BOOLEAN     NOT NULL DEFAULT FALSE,
            runner_3b_scored            BOOLEAN     NOT NULL DEFAULT FALSE,
            runner_1b_out_advancing     BOOLEAN     NOT NULL DEFAULT FALSE,
            runner_2b_out_advancing     BOOLEAN     NOT NULL DEFAULT FALSE,
            runner_3b_out_advancing     BOOLEAN     NOT NULL DEFAULT FALSE,
            sb_attempt_2b               BOOLEAN     NOT NULL DEFAULT FALSE,
            sb_attempt_3b               BOOLEAN     NOT NULL DEFAULT FALSE,
            sb_attempt_home             BOOLEAN     NOT NULL DEFAULT FALSE,
            sb_success_2b               BOOLEAN     NOT NULL DEFAULT FALSE,
            sb_success_3b               BOOLEAN     NOT NULL DEFAULT FALSE,
            sb_success_home             BOOLEAN     NOT NULL DEFAULT FALSE,
            passed_ball_wild_pitch      BOOLEAN     NOT NULL DEFAULT FALSE,
            pinch_hitter                BOOLEAN     NOT NULL DEFAULT FALSE,
            pinch_runner                BOOLEAN     NOT NULL DEFAULT FALSE,
            pitcher_sub                 BOOLEAN     NOT NULL DEFAULT FALSE,
            defensive_sub               BOOLEAN     NOT NULL DEFAULT FALSE,
            fielded_by                  INTEGER,
            fielding_error              INTEGER,
            dropped_ball                INTEGER,
            of_assist                   INTEGER,
            field_assist_1              INTEGER,
            field_assist_2              INTEGER,
            field_assist_3              INTEGER,
            field_assist_4              INTEGER,
            field_assist_5              INTEGER,
            field_putout_1              INTEGER,
            field_putout_2              INTEGER,
            field_putout_3              INTEGER,
            throwing_error_1            INTEGER,
            throwing_error_2            INTEGER,
            data_quality_flag           BOOLEAN     NOT NULL DEFAULT FALSE,
            created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            PRIMARY KEY (game_pk, at_bat_number, pitch_number),
            FOREIGN KEY (venue_id, season)          REFERENCES raw.venues(venue_id, season),
            FOREIGN KEY (home_id, season)           REFERENCES raw.teams(team_id, season),
            FOREIGN KEY (away_id, season)           REFERENCES raw.teams(team_id, season),
            FOREIGN KEY (home_manager_id, season)   REFERENCES raw.managers(manager_id, season),
            FOREIGN KEY (away_manager_id, season)   REFERENCES raw.managers(manager_id, season),
            CONSTRAINT chk_pitches_sb_logic CHECK (
                (NOT sb_success_2b   OR sb_attempt_2b)   AND
                (NOT sb_success_3b   OR sb_attempt_3b)   AND
                (NOT sb_success_home OR sb_attempt_home)
            )
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS idx_pitches_pitcher        ON raw.pitches(pitcher)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_pitches_batter         ON raw.pitches(batter)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_pitches_game_date      ON raw.pitches(game_date)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_pitches_venue          ON raw.pitches(venue_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_pitches_pitch_type     ON raw.pitches(pitch_type)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_pitches_events         ON raw.pitches(events) WHERE events IS NOT NULL")
    op.execute("CREATE INDEX IF NOT EXISTS idx_pitches_pitcher_season ON raw.pitches(pitcher, game_date)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_pitches_batter_season  ON raw.pitches(batter, game_date)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_pitches_pitcher_type   ON raw.pitches(pitcher, pitch_type)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_pitches_sb_attempts    ON raw.pitches(pitcher, fielder_2) WHERE sb_attempt_2b OR sb_attempt_3b OR sb_attempt_home")
    op.execute("CREATE INDEX IF NOT EXISTS idx_pitches_subs           ON raw.pitches(game_pk) WHERE pitcher_sub OR pinch_hitter OR pinch_runner OR defensive_sub")
    op.execute("CREATE INDEX IF NOT EXISTS idx_pitches_batted_balls   ON raw.pitches(batter, pitcher, game_date) WHERE type = 'X'")
    op.execute("CREATE INDEX IF NOT EXISTS idx_pitches_quality_clean  ON raw.pitches(game_date) WHERE data_quality_flag = FALSE")
    op.execute("CREATE INDEX IF NOT EXISTS idx_pitches_count_state    ON raw.pitches(balls, strikes, outs)")

    # -----------------------------------------------------------------
    # sim.lineup_state
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE IF NOT EXISTS sim.lineup_state (
            session_id              UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
            game_pk                 INTEGER,
            is_live_game            BOOLEAN     NOT NULL DEFAULT FALSE,
            game_state              JSONB       NOT NULL,
            selected_at_bat         INTEGER,
            selected_pitch          INTEGER,
            pending_substitution    JSONB,
            simulation_results      JSONB,
            iterations_run          INTEGER     NOT NULL DEFAULT 0,
            created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            expires_at              TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '24 hours')
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS idx_lineup_state_game_pk        ON sim.lineup_state(game_pk) WHERE game_pk IS NOT NULL")
    op.execute("CREATE INDEX IF NOT EXISTS idx_lineup_state_live           ON sim.lineup_state(is_live_game, updated_at) WHERE is_live_game = TRUE")
    op.execute("CREATE INDEX IF NOT EXISTS idx_lineup_state_expires        ON sim.lineup_state(expires_at)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_lineup_state_game_state_gin ON sim.lineup_state USING GIN(game_state)")

    # -----------------------------------------------------------------
    # Triggers
    # -----------------------------------------------------------------
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER LANGUAGE plpgsql AS $$
        BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
        $$
    """)
    for tbl in ("raw.venues", "raw.teams", "raw.players", "raw.managers",
                "raw.games", "raw.game_lineups", "sim.lineup_state"):
        short = tbl.split(".")[1]
        op.execute(f"""
            CREATE TRIGGER trg_{short}_updated_at
                BEFORE UPDATE ON {tbl}
                FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()
        """)

    op.execute("""
        CREATE OR REPLACE FUNCTION raw.flag_pitch_quality()
        RETURNS TRIGGER LANGUAGE plpgsql AS $$
        BEGIN
            IF (
                (NEW.release_speed IS NOT NULL AND (NEW.release_speed > 102 OR NEW.release_speed < 60)) OR
                (NEW.launch_speed  IS NOT NULL AND NEW.launch_speed > 125) OR
                (NEW.break_vertical_induced IS NOT NULL AND
                    (NEW.break_vertical_induced < -25 OR NEW.break_vertical_induced > 25))
            ) THEN
                NEW.data_quality_flag = TRUE;
            END IF;
            RETURN NEW;
        END;
        $$
    """)
    op.execute("""
        CREATE TRIGGER trg_pitches_quality_flag
            BEFORE INSERT ON raw.pitches
            FOR EACH ROW EXECUTE FUNCTION raw.flag_pitch_quality()
    """)

    # -----------------------------------------------------------------
    # Utility functions + view
    # -----------------------------------------------------------------
    op.execute("""
        CREATE OR REPLACE FUNCTION sim.purge_expired_sessions()
        RETURNS INTEGER LANGUAGE plpgsql AS $$
        DECLARE deleted_count INTEGER;
        BEGIN
            DELETE FROM sim.lineup_state WHERE expires_at < NOW() AND is_live_game = FALSE;
            GET DIAGNOSTICS deleted_count = ROW_COUNT;
            RETURN deleted_count;
        END;
        $$
    """)
    op.execute("""
        CREATE OR REPLACE VIEW sim.live_games AS
        SELECT
            g.game_pk, g.game_date, g.status,
            g.home_team_id, g.away_team_id,
            g.home_score_final, g.away_score_final,
            g.venue_id,
            ls.session_id,
            ls.updated_at   AS last_sim_update,
            ls.iterations_run
        FROM  raw.games g
        LEFT  JOIN sim.lineup_state ls ON ls.game_pk = g.game_pk AND ls.is_live_game = TRUE
        WHERE g.status = 'Live' AND g.game_date = CURRENT_DATE
    """)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS sim.live_games")
    op.execute("DROP FUNCTION IF EXISTS sim.purge_expired_sessions()")
    op.execute("DROP TABLE IF EXISTS sim.lineup_state CASCADE")
    op.execute("DROP TABLE IF EXISTS raw.pitches CASCADE")
    op.execute("DROP TABLE IF EXISTS raw.sprint_speed CASCADE")
    op.execute("DROP TABLE IF EXISTS raw.game_lineups CASCADE")
    op.execute("DROP TABLE IF EXISTS raw.games CASCADE")
    op.execute("DROP TABLE IF EXISTS raw.managers CASCADE")
    op.execute("DROP TABLE IF EXISTS raw.players CASCADE")
    op.execute("DROP TABLE IF EXISTS raw.teams CASCADE")
    op.execute("DROP TABLE IF EXISTS raw.venues CASCADE")
    op.execute("DROP SCHEMA IF EXISTS sim CASCADE")
    op.execute("DROP SCHEMA IF EXISTS raw CASCADE")
