/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/betting/games/{game_pk}/clv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Entry-vs-close CLV snapshot per side/book
         * @description A thin projection of /line-movement: the line-movement series that carry an entry-vs-close CLV (>= 2 quotes with both opposite-side prices). Each model's clv.clv_prob / clv.beat_close answers 'did the opening price beat the close' for that side/book. numpy-free. 503 if no DB pool, 422 on a bad market_type.
         */
        get: operations["get_game_clv_api_betting_games__game_pk__clv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/betting/games/{game_pk}/edges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Per-market edge reports (moneyline / total / run-line)
         * @description Run (or reuse, via the SIM-359 cache) a Monte-Carlo sim for the game and build the EdgeReports for the requested markets (moneyline / total / runline, both sides each) off the GameSimSummary + market odds. Odds come from the injected query params when supplied, else the deterministic mock provider (flagged per market in odds_source). numpy-free EdgeReportModel list. 503 if no DB pool, 404 if the lineup cannot be resolved, 422 on a bad market.
         */
        get: operations["get_game_edges_api_betting_games__game_pk__edges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/betting/games/{game_pk}/line-movement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Opening->closing line-movement time-series per side/book
         * @description Read the persisted raw.game_odds history for the (game_pk, market_type[, book]) and build the SIM-368 line-movement time-series: one series per (side, book) with the ordered quotes, the per-step + opening->closing deltas, the running implied-prob surface, the steam direction, the sharp-consensus flag, and the entry-vs-close CLV. numpy-free LineMovementModel list. 503 if no DB pool, 422 on a bad market_type.
         */
        get: operations["get_game_line_movement_api_betting_games__game_pk__line_movement_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/betting/games/{game_pk}/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ranked +EV bet-signal recommendations
         * @description Build the per-market EdgeReports (as /edges), gate them to the +EV set (strictly positive edge >= min_edge AND ev > min_ev), size each via fractional Kelly (kelly_fraction, capped at max_stake_fraction), and return them RANKED by EV descending. min_edge / kelly_fraction are tunable via query params. numpy-free BetSignalModel list. 503 if no DB pool, 404 if the lineup cannot be resolved, 422 on a bad market.
         */
        get: operations["get_game_signals_api_betting_games__game_pk__signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/freshness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ingest freshness + per-season coverage for the UI
         * @description Aggregate view of the ingested data: the last-ingest watermark (raw.etl_data_freshness), the most-recent game date with data, total games/pitches, and per-season coverage. The frontend uses this for a 'data as of …' badge and an empty/stale-store warning. 503 when no DB pool is attached; an empty store returns zeros (not an error).
         */
        get: operations["get_data_freshness_api_data_freshness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Games scheduled on a date
         * @description List the games on a date (YYYY-MM-DD) from raw.games. The result is memoized at POOL_QUERY_TTL_S (300s) when a sim cache is attached (SIM-359). Returns 503 if no DB pool is attached, 422 on a bad date.
         */
        get: operations["get_games_on_date_api_games__date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_pk}/boxscore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Per-player boxscore-average card (prop means over N iterations)
         * @description Resolve the game's lineup, run an N-iteration boxscore batch, and return each player's prop MEANS as a boxscore card (SIM-366): for a batter the H/HR/RBI/TB means, for a pitcher the K/BB/ER/OUTS means -- the means-only projection of the run's PropDistributionSet (SIM-329). numpy-free JSON (SIM-350). 503 if no DB pool is attached; 404 if the lineup cannot be resolved.
         */
        get: operations["get_game_boxscore_api_games__game_pk__boxscore_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_pk}/card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Combined linescore + pitcher decisions for a simulated game
         * @description Return BOTH the per-inning linescore (SIM-362) and the W/L/Save pitcher decisions (SIM-364) for the game's most-recent persisted run in one payload, from the DuckDB game-card store. 404 if no card has been persisted, 503 if no replay store is wired.
         */
        get: operations["get_game_card_api_games__game_pk__card_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_pk}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Winning/losing/save pitcher decisions for a simulated game
         * @description Return the persisted W/L/Save pitcher decisions (SIM-364) for the game's most-recent persisted run -- derived at record time from the recorded PlayResult stream by /simulate and served from the DuckDB game-card store. All three pitcher ids are null on a tie / no-decision. numpy-free JSON. 404 if no card has been persisted, 503 if no replay store is wired.
         */
        get: operations["get_game_decisions_api_games__game_pk__decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_pk}/linescore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Per-inning linescore (R/H/E grid) for a simulated game
         * @description Return the persisted per-inning linescore (the away/home run grid plus each team's Runs/Hits/Errors totals, SIM-362) for the game's most-recent persisted run -- derived at record time from the recorded PlayResult stream by /simulate and served from the DuckDB game-card store. numpy-free JSON (SIM-350). 404 if no card has been persisted, 503 if no replay store is wired.
         */
        get: operations["get_game_linescore_api_games__game_pk__linescore_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_pk}/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live in-progress game state (SIM-386)
         * @description Read the live game state from ``sim.lineup_state`` for an in-progress game.  The live ingestion pipeline (port :8001) writes the game state JSONB on every MLB WebSocket signal; this endpoint surfaces it on the main API so the frontend does not need to reach the pipeline app directly.  Fields mirror the ``game_state`` JSONB blob: inning/half/outs/score/baserunners/lineup/roster.  ``updated_at`` (ISO-8601) marks when the pipeline last wrote; the frontend may treat a gap > 30s as a potential pipeline staleness signal.  Returns 404 when no live row exists for ``game_pk`` (game not yet live, already finished, or pipeline has not ingested it yet). Returns 503 when no DB pool is attached.
         */
        get: operations["get_live_game_state_api_games__game_pk__live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_pk}/plays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Play-by-play scroll for a simulated game
         * @description Return the persisted pitch-level play-by-play (one entry per pitch, the resolved PA event on the terminal pitch) for the game's most-recent persisted run -- the durable backing populated by /simulate (SIM-357). Served straight from the DuckDB play-stream store (SIM-356); numpy-free JSON (SIM-350). SIM-415: optional ``limit``/``offset`` page the entries (a full game is ~300 pitches); ``n_pitches``/``n_plate_appearances`` stay full-game totals and ``total_entries``/``page_*`` describe the slice. Omitting ``limit`` returns the whole stream (unchanged shape). 404 if nothing has been persisted for the game, 503 if no replay store is wired.
         */
        get: operations["get_game_plays_api_games__game_pk__plays_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_pk}/props/{player_id}/{prop}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Player prop PMF + optional edge report (SIM-390)
         * @description Run an N-iteration Monte-Carlo batch for the game, look up one player's prop PMF (e.g. K, BB, H, HR), and return the full integer-support PMF.  Supply ``line`` to also get ``p_over``/``p_under``/``p_push``; supply ``line``, ``over_ml``, and ``under_ml`` to also get a full ``edge_report`` via the CLV engine (SIM-339).  ``bet_side`` controls which side's edge is computed (``'over'`` or ``'under'``, default ``'over'``).  Valid props: K, BB, ER, OUTS (pitcher), H, HR, RBI, TB (batter).  503 if no DB pool is attached; 404 if the lineup or player cannot be resolved.
         */
        get: operations["get_player_prop_edge_api_games__game_pk__props__player_id___prop__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_pk}/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Simulate a game (Monte-Carlo)
         * @description Resolve the game's lineup into a GameState (SIM-353), run an N-iteration Monte-Carlo batch (SIM-332), and return the GameSimSummary (numpy-free JSON, SIM-350). The machine factory is the testability seam (see resolve_factory_ref). Summary results are cached at SIM_RESULT_TTL_S (60s) keyed on (spec + seed + N) -- SIM-359.
         */
        get: operations["simulate_game_endpoint_api_games__game_pk__simulate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_pk}/simulate/with_override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate a game with a roster override (baseline vs override)
         * @description Run a BASELINE sim (resolved lineup) and an OVERRIDE sim (the modified roster) at the SAME base seed, then return both summaries plus the baseline-vs-override OverrideDelta (SIM-331). The factory + caching seams are shared with /simulate (SIM-355/SIM-359).
         */
        post: operations["simulate_with_override_endpoint_api_games__game_pk__simulate_with_override_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_pk}/state/{at_bat}/{pitch}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Field/state snapshot as of a given at-bat/pitch
         * @description Return the point-in-time field/baserunner/count snapshot as of the given (at_bat, pitch) for the game's most-recent persisted run -- the StateAtPitch persisted by /simulate (SIM-357), served from the DuckDB state-snapshot store. numpy-free JSON (SIM-350). 404 if no snapshot was persisted for that pitch, 503 if no replay store is wired.
         */
        get: operations["get_game_state_at_pitch_api_games__game_pk__state__at_bat___pitch__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_pk}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Game-status aggregate (identity + 3-state status + sim summary)
         * @description Return a single game's enriched identity (SIM-383 team names + records + venue), 3-state status enum (scheduled/live/final/postponed), final scores when available, and the most recently persisted Monte-Carlo sim summary as a lite projection (no raw score arrays). Intended for the Day Summary 3-state game cards (SIM-391). ``sim_summary`` is None when no sim has been run yet or when Postgres is unavailable. ``odds`` is reserved for the Phase-6 odds-provider integration (SIM-405). Returns 404 when game_pk is not in raw.games, 503 when no DB pool is attached.
         */
        get: operations["get_game_status_card_api_games__game_pk__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/odds/today/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Todays Odds
         * @description Returns mock odds for every game scheduled today.
         */
        get: operations["get_todays_odds_api_odds_today_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/odds/{game_pk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Game Odds
         * @description Returns mock betting lines for a game.  In Phase 7, replace this handler
         *     with a call to a real odds provider and flip is_mock=False.
         */
        get: operations["get_game_odds_api_odds__game_pk__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/similarity/pitcher/{pitcher_id}/{season}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pitcher similarity score distribution
         * @description Returns the full similarity-score distribution between the query pitcher-season and every same-handedness pitcher-season in the engine, binned for the histogram view. See ``docs/similarity_visualization_spec.md`` for the full design.
         */
        get: operations["get_pitcher_similarity_distribution_api_similarity_pitcher__pitcher_id___season__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange password for session cookie
         * @description Validate the shared AUTH_PASSWORD and issue an httpOnly session cookie (sim_session). The cookie is Secure + SameSite=strict in non-development environments. Session lifetime is SESSION_TTL_HOURS (default 8 hours). Returns 401 on an incorrect password.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear the session cookie
         * @description Expire the sim_session cookie.  Always returns 200 (idempotent).
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check current session state
         * @description Probe whether the caller has a valid session.  Always returns 200 (never 401) so the frontend can call this on boot to decide whether to show the login page without triggering an error flow.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 when the application is ready to serve traffic.
         *     Confirms the Postgres pool, the Redis cache, and the pitcher
         *     similarity engine are all attached and (for DB/Redis) live.
         *
         *     Returns 503 with a per-component status if any check fails. A
         *     missing pitcher_engine is reported but does NOT cause /ready to
         *     fail — the similarity route surfaces that via its own 503.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthStatusResponse
         * @description Response for GET /auth/me — always 200, never 401.
         */
        AuthStatusResponse: {
            /** Authenticated */
            authenticated: boolean;
            /** Expires In */
            expires_in: number;
            /** Mode */
            mode: string;
        };
        /**
         * BetSignalModel
         * @description Response model for :class:`betting.bet_signal.BetSignal` (SIM-369).
         *
         *     A fireable +EV bet recommendation derived from one :class:`EdgeReport`.
         *     ``side`` is the MarketSide enum's ``.value`` (a JSON-native string, e.g.
         *     "home" / "over"); ``report`` is the full source :class:`EdgeReportModel` (so a
         *     consumer gets the sim/market probabilities + CLV behind the signal). The list
         *     a signals endpoint returns is already ranked by EV descending (``rank`` 0 ==
         *     strongest). numpy-free (plain floats / ints).
         */
        BetSignalModel: {
            /** Confidence */
            confidence: number;
            /** Edge */
            edge: number;
            /** Ev */
            ev: number;
            /** Label */
            label: string;
            /** Line */
            line?: number | null;
            /** Offered American */
            offered_american: number;
            /** Rank */
            rank: number;
            report: components["schemas"]["EdgeReportModel"];
            /** Side */
            side: string;
            /** Stake Fraction */
            stake_fraction: number;
        };
        /**
         * BoxscoreCardModel
         * @description Response model for the SIM-366 per-player boxscore-average card.
         *
         *     The boxscore-card payload for one Monte-Carlo run: every player's prop
         *     **means** (the 100-iteration boxscore average) keyed
         *     ``str(player_id) -> BoxscoreCardRowModel`` (JSON object keys must be strings).
         *     Built from a :class:`simulation.prop_distributions.PropDistributionSet` via
         *     :meth:`from_prop_set`, iterating ``by_player`` and reading each
         *     :attr:`PropDistribution.mean` -- so the card is the means-only projection of
         *     the full PMF set (a consumer that needs the full PMF reads the heavier
         *     :class:`PropDistributionSetModel` instead).  numpy-free.
         */
        BoxscoreCardModel: {
            /** N Iterations */
            n_iterations: number;
            /** Players */
            players?: {
                [key: string]: components["schemas"]["BoxscoreCardRowModel"];
            };
        };
        /**
         * BoxscoreCardRowModel
         * @description One player's row in the SIM-366 boxscore card.
         *
         *     A compact per-player payload exposing that player's prop **means** over a
         *     Monte-Carlo run -- for a batter the H/HR/RBI/TB means, for a pitcher the
         *     K/BB/ER/OUTS means -- as a ``{prop_name -> mean}`` map.  Built from a
         *     :class:`simulation.prop_distributions.PropDistribution` map (one player's
         *     ``by_player`` entry), reading each :attr:`PropDistribution.mean`.  numpy-free
         *     (plain floats).
         */
        BoxscoreCardRowModel: {
            /** Means */
            means?: {
                [key: string]: number;
            };
            /** Player Id */
            player_id: number;
        };
        /**
         * CLVModel
         * @description Response model for :class:`betting.clv_engine.CLV` (SIM-339).
         *
         *     Closing Line Value for one side of one market/prop.  ``beat_close`` mirrors
         *     the source dataclass's derived property (clv_prob > 0).
         */
        CLVModel: {
            /** Beat Close */
            beat_close: boolean;
            /** Close Fair Decimal */
            close_fair_decimal: number;
            /** Close Fair Prob */
            close_fair_prob: number;
            /** Clv Decimal */
            clv_decimal: number;
            /** Clv Prob */
            clv_prob: number;
            /** Entry Fair Decimal */
            entry_fair_decimal: number;
            /** Entry Fair Prob */
            entry_fair_prob: number;
        };
        /**
         * ClvSnapshotResponse
         * @description The ``GET /api/betting/games/{game_pk}/clv`` envelope.
         *
         *     A thin snapshot projection of /line-movement: the entry-vs-close CLV of every
         *     line-movement series that HAS one (a series with < 2 quotes or a missing
         *     opposite-side price is omitted). Each row carries the side / book identity plus
         *     the CLV's ``clv_prob`` / ``beat_close`` for a compact "did I beat the close"
         *     view without the full quote series.
         */
        ClvSnapshotResponse: {
            /** Book */
            book?: string | null;
            /**
             * Count
             * @default 0
             */
            count: number;
            /** Game Pk */
            game_pk: number;
            /** Market Type */
            market_type: string;
            /** Series */
            series?: components["schemas"]["LineMovementModel"][];
        };
        /**
         * ConfidenceIntervalModel
         * @description Response model for :class:`simulation.results.ConfidenceInterval`.
         *
         *     A two-sided interval around ``point`` (``low <= point <= high``).  ``level``
         *     is the nominal confidence (e.g. 0.95); ``method`` names how it was computed.
         *     ``half_width`` mirrors the dataclass's derived property for consumer
         *     convenience (it is not a stored field on the source).
         */
        ConfidenceIntervalModel: {
            /** Half Width */
            half_width: number;
            /** High */
            high: number;
            /**
             * Level
             * @default 0.95
             */
            level: number;
            /** Low */
            low: number;
            /**
             * Method
             * @default normal
             */
            method: string;
            /** Point */
            point: number;
        };
        /**
         * DataFreshnessResponse
         * @description Aggregate ingest freshness + coverage for the UI.
         */
        DataFreshnessResponse: {
            /**
             * Has Data
             * @default false
             */
            has_data: boolean;
            /** Last Ingest At */
            last_ingest_at?: string | null;
            /** Latest Game Date */
            latest_game_date?: string | null;
            /** Seasons */
            seasons?: components["schemas"]["SeasonCoverage"][];
            /**
             * Total Games
             * @default 0
             */
            total_games: number;
            /**
             * Total Pitches
             * @default 0
             */
            total_pitches: number;
            /**
             * Tracked Entities
             * @default 0
             */
            tracked_entities: number;
        };
        /**
         * EdgeReportModel
         * @description Response model for :class:`betting.clv_engine.EdgeReport` (SIM-339).
         *
         *     The full edge / EV / CLV report for one side of one market or prop.  ``side``
         *     is the MarketSide enum's ``.value`` (a JSON-native string, e.g. "home" /
         *     "over"); ``clv`` is present only when a closing quote was supplied.
         *     ``positive_edge`` mirrors the source's derived property (edge > 0).
         */
        EdgeReportModel: {
            clv?: components["schemas"]["CLVModel"] | null;
            /** Edge */
            edge: number;
            /** Ev */
            ev: number;
            /** Label */
            label: string;
            /** Line */
            line?: number | null;
            /** Market Fair Prob */
            market_fair_prob: number;
            /** Offered American */
            offered_american: number;
            /** Positive Edge */
            positive_edge: boolean;
            /** Side */
            side: string;
            /** Sim Fair American */
            sim_fair_american: number;
            /** Sim Prob */
            sim_prob: number;
        };
        /**
         * EdgesResponse
         * @description The ``GET /api/betting/games/{game_pk}/edges`` envelope.
         *
         *     Carries the per-market :class:`EdgeReportModel` list plus the run metadata
         *     (n_iterations / base_seed) and the per-market ``odds_source`` flags
         *     ("injected" / "mock") so a consumer knows where each market's prices came from.
         */
        EdgesResponse: {
            /** Base Seed */
            base_seed?: number | null;
            /** Edges */
            edges?: components["schemas"]["EdgeReportModel"][];
            /** Game Pk */
            game_pk: number;
            /** Markets */
            markets?: string[];
            /** N Iterations */
            n_iterations: number;
            /** Odds Source */
            odds_source?: {
                [key: string]: string;
            };
        };
        /**
         * FieldSnapshotModel
         * @description Response model for :class:`simulation.snapshots.FieldSnapshot` (SIM-331).
         *
         *     The BaseballFieldGraphic state: 9 defensive positions + batter + baserunners
         *     + count/outs/inning/half/score chrome.  ``positions`` and ``baserunners`` map
         *     a label to an OPTIONAL :class:`PlayerRefModel` (``None`` == unassigned slot /
         *     empty bag).  ``occupied_bases`` / ``runners_on`` mirror the source's derived
         *     properties for consumer convenience.
         */
        FieldSnapshotModel: {
            /** Away Score */
            away_score: number;
            /** Balls */
            balls: number;
            /** Baserunners */
            baserunners: {
                [key: string]: components["schemas"]["PlayerRefModel"] | null;
            };
            batter?: components["schemas"]["PlayerRefModel"] | null;
            /** Half */
            half: string;
            /** Home Score */
            home_score: number;
            /** Inning */
            inning: number;
            /** Occupied Bases */
            occupied_bases: string[];
            /** Outs */
            outs: number;
            /** Positions */
            positions: {
                [key: string]: components["schemas"]["PlayerRefModel"] | null;
            };
            /** Runners On */
            runners_on: number;
            /**
             * Runners State
             * @default 0
             */
            runners_state: number;
            /** Strikes */
            strikes: number;
        };
        /**
         * GameCard
         * @description One row of ``GET /api/games/{date}`` -- a scheduled game's identity.
         *
         *     SIM-383 enrichment adds team names, abbreviations, venue name + city, and
         *     season-to-date win/loss records (computed through the day before ``game_date``
         *     from ``raw.games`` final results).  All enrichment fields are ``Optional``
         *     so existing cached payloads and unit-test stubs that only supply the raw
         *     ID columns continue to deserialise without error.
         */
        GameCard: {
            /** Away Losses */
            away_losses?: number | null;
            /** Away Team Abbrev */
            away_team_abbrev?: string | null;
            /** Away Team Id */
            away_team_id?: number | null;
            /** Away Team Name */
            away_team_name?: string | null;
            /** Away Wins */
            away_wins?: number | null;
            /** Game Date */
            game_date: string;
            /** Game Pk */
            game_pk: number;
            /** Home Losses */
            home_losses?: number | null;
            /** Home Team Abbrev */
            home_team_abbrev?: string | null;
            /** Home Team Id */
            home_team_id?: number | null;
            /** Home Team Name */
            home_team_name?: string | null;
            /** Home Wins */
            home_wins?: number | null;
            /** Season */
            season: number;
            /** Status */
            status?: string | null;
            /** Venue City */
            venue_city?: string | null;
            /** Venue Id */
            venue_id?: number | null;
            /** Venue Name */
            venue_name?: string | null;
        };
        /**
         * GameCardAggregateResponse
         * @description Response for ``GET /api/games/{game_pk}/card`` (SIM-384).
         *
         *     Aggregates the identity, status, SIM-383 enrichment, and the most recent
         *     persisted Monte-Carlo summary into a single payload for the Day Summary
         *     3-state game cards.  ``sim_summary`` is ``None`` when no sim has been run
         *     yet (or when Postgres is unavailable).  ``odds`` is reserved for Phase 6
         *     Sprint 4+ (odds provider integration — SIM-405).
         */
        GameCardAggregateResponse: {
            /** Away Losses */
            away_losses?: number | null;
            /** Away Score Final */
            away_score_final?: number | null;
            /** Away Team Abbrev */
            away_team_abbrev?: string | null;
            /** Away Team Id */
            away_team_id?: number | null;
            /** Away Team Name */
            away_team_name?: string | null;
            /** Away Wins */
            away_wins?: number | null;
            /** Game Date */
            game_date: string;
            /** Game Pk */
            game_pk: number;
            /** Game Status */
            game_status: string;
            /** Home Losses */
            home_losses?: number | null;
            /** Home Score Final */
            home_score_final?: number | null;
            /** Home Team Abbrev */
            home_team_abbrev?: string | null;
            /** Home Team Id */
            home_team_id?: number | null;
            /** Home Team Name */
            home_team_name?: string | null;
            /** Home Wins */
            home_wins?: number | null;
            /** Odds */
            odds?: null;
            /** Season */
            season: number;
            sim_summary?: components["schemas"]["GameSimSummaryLite"] | null;
            /** Venue City */
            venue_city?: string | null;
            /** Venue Id */
            venue_id?: number | null;
            /** Venue Name */
            venue_name?: string | null;
        };
        /**
         * GameCardResponse
         * @description The combined ``GET /api/games/{game_pk}/card`` envelope (SIM-362/364).
         *
         *     Carries both derived loop outputs for the game's most-recent persisted run:
         *     the per-inning :class:`~api.schemas.LinescoreModel` (R/H/E grid) and the
         *     :class:`~api.schemas.PitcherDecisionsModel` (W/L/Save).
         */
        GameCardResponse: {
            decisions: components["schemas"]["PitcherDecisionsModel"];
            /** Game Pk */
            game_pk: number;
            linescore: components["schemas"]["LinescoreModel"];
        };
        /**
         * GameSimSummaryLite
         * @description A raw-array-FREE projection of :class:`simulation.results.GameSimSummary`.
         *
         *     Identical to :class:`GameSimSummaryModel` minus the three large
         *     per-iteration score arrays -- the right shape for a list / index endpoint
         *     that wants the aggregates (win %, means, CIs) but not the full distribution.
         *     Build via :meth:`from_dataclass`.
         */
        GameSimSummaryLite: {
            away_score_ci: components["schemas"]["ConfidenceIntervalModel"];
            /** Away Score Mean */
            away_score_mean: number;
            /** Away Score Median */
            away_score_median: number;
            away_win_ci: components["schemas"]["ConfidenceIntervalModel"];
            /** Away Win Pct */
            away_win_pct: number;
            /**
             * Ci Method
             * @default normal
             */
            ci_method: string;
            /**
             * Confidence Level
             * @default 0.95
             */
            confidence_level: number;
            home_score_ci: components["schemas"]["ConfidenceIntervalModel"];
            /** Home Score Mean */
            home_score_mean: number;
            /** Home Score Median */
            home_score_median: number;
            home_win_ci: components["schemas"]["ConfidenceIntervalModel"];
            /** Home Win Pct */
            home_win_pct: number;
            /** N Iterations */
            n_iterations: number;
            /** Simulated At */
            simulated_at: string;
            /** Tie Pct */
            tie_pct: number;
            total_score_ci: components["schemas"]["ConfidenceIntervalModel"];
            /** Total Score Mean */
            total_score_mean: number;
            /** Total Score Median */
            total_score_median: number;
        };
        /**
         * GameSimSummaryModel
         * @description Response model for :class:`simulation.results.GameSimSummary` (SIM-327).
         *
         *     The RAW per-iteration arrays (``home_scores`` / ``away_scores`` /
         *     ``total_scores``) are exposed as ``list[int]`` and are OPTIONAL on the wire:
         *     they are present by default but an endpoint may build the model with
         *     ``include_raw_arrays=False`` (or use :class:`GameSimSummaryLite`) to omit
         *     them for a list/index view -- see the module docstring's "large per-iteration
         *     arrays" note.  When omitted they serialise as ``None`` (never a partial /
         *     down-sampled array).
         */
        GameSimSummaryModel: {
            away_score_ci: components["schemas"]["ConfidenceIntervalModel"];
            /** Away Score Mean */
            away_score_mean: number;
            /** Away Score Median */
            away_score_median: number;
            /** Away Scores */
            away_scores?: number[] | null;
            away_win_ci: components["schemas"]["ConfidenceIntervalModel"];
            /** Away Win Pct */
            away_win_pct: number;
            /**
             * Ci Method
             * @default normal
             */
            ci_method: string;
            /**
             * Confidence Level
             * @default 0.95
             */
            confidence_level: number;
            home_score_ci: components["schemas"]["ConfidenceIntervalModel"];
            /** Home Score Mean */
            home_score_mean: number;
            /** Home Score Median */
            home_score_median: number;
            /** Home Scores */
            home_scores?: number[] | null;
            home_win_ci: components["schemas"]["ConfidenceIntervalModel"];
            /** Home Win Pct */
            home_win_pct: number;
            /** N Iterations */
            n_iterations: number;
            /** Simulated At */
            simulated_at: string;
            /** Tie Pct */
            tie_pct: number;
            total_score_ci: components["schemas"]["ConfidenceIntervalModel"];
            /** Total Score Mean */
            total_score_mean: number;
            /** Total Score Median */
            total_score_median: number;
            /** Total Scores */
            total_scores?: number[] | null;
        };
        /**
         * GamesOnDateResponse
         * @description The ``GET /api/games/{date}`` envelope: the date echo + its game cards.
         */
        GamesOnDateResponse: {
            /** Count */
            count: number;
            /** Date */
            date: string;
            /** Games */
            games?: components["schemas"]["GameCard"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InningLineModel
         * @description Response model for :class:`simulation.linescore.InningLine` (SIM-362).
         *
         *     One inning's away (top) / home (bottom) run cells.  ``away`` / ``home`` are
         *     ``Optional[int]``: ``None`` is the classic scoreboard "x" (a half that was
         *     never played -- e.g. the bottom of the final inning when the home team already
         *     leads, or a walk-off), distinguished from ``0`` (played and scoreless).
         *     ``away_played`` / ``home_played`` mirror the source's derived properties.
         */
        InningLineModel: {
            /** Away */
            away?: number | null;
            /** Away Played */
            away_played: boolean;
            /** Home */
            home?: number | null;
            /** Home Played */
            home_played: boolean;
            /** Inning */
            inning: number;
        };
        /**
         * LineMovementModel
         * @description Response model for :class:`betting.line_movement.LineMovement` (SIM-368).
         *
         *     The line-movement time-series for one (game_pk, market, side, book): the
         *     ordered :class:`LineQuoteModel` series plus the derived opening->closing
         *     summary (the American / implied-prob / line deltas, the per-step delta series,
         *     the running ``implied_prob_series`` plottable surface, the steam ``direction``)
         *     and the entry-vs-close :class:`CLVModel`. ``side`` is the MarketSide enum's
         *     ``.value``; ``has_movement`` / ``beat_close`` mirror the source's derived
         *     properties. numpy-free (plain floats).
         */
        LineMovementModel: {
            /** American Delta */
            american_delta?: number | null;
            /**
             * Beat Close
             * @default false
             */
            beat_close: boolean;
            /** Book */
            book?: string | null;
            /** Closing American */
            closing_american?: number | null;
            /** Closing Implied Prob */
            closing_implied_prob?: number | null;
            clv?: components["schemas"]["CLVModel"] | null;
            /**
             * Direction
             * @default flat
             */
            direction: string;
            /** Game Pk */
            game_pk: number;
            /**
             * Has Movement
             * @default false
             */
            has_movement: boolean;
            /** Implied Prob Delta */
            implied_prob_delta?: number | null;
            /** Implied Prob Series */
            implied_prob_series?: number[];
            /** Line Delta */
            line_delta?: number | null;
            /** Market Type */
            market_type: string;
            /** Opening American */
            opening_american?: number | null;
            /** Opening Implied Prob */
            opening_implied_prob?: number | null;
            /** Quotes */
            quotes?: components["schemas"]["LineQuoteModel"][];
            /** Sharp Consensus */
            sharp_consensus?: boolean | null;
            /** Side */
            side: string;
            /** Step American Deltas */
            step_american_deltas?: number[];
            /** Step Implied Prob Deltas */
            step_implied_prob_deltas?: number[];
        };
        /**
         * LineMovementResponse
         * @description The ``GET /api/betting/games/{game_pk}/line-movement`` envelope.
         *
         *     Carries one :class:`LineMovementModel` per (side, book) present in the stored
         *     ``raw.game_odds`` history for the (game_pk, market_type[, book]).
         */
        LineMovementResponse: {
            /** Book */
            book?: string | null;
            /**
             * Count
             * @default 0
             */
            count: number;
            /** Game Pk */
            game_pk: number;
            /** Market Type */
            market_type: string;
            /** Series */
            series?: components["schemas"]["LineMovementModel"][];
        };
        /**
         * LineQuoteModel
         * @description Response model for :class:`betting.line_movement.LineQuote` (SIM-368).
         *
         *     One timestamped quote for a single side of one market at one book -- a point
         *     on the line-movement time-series. ``fetched_at`` is rendered as a string (a
         *     datetime is ISO-8601'd via :func:`api.serialization.to_jsonable`, an already-
         *     string timestamp passes through). ``implied_prob`` is the RAW single-side
         *     implied probability. numpy-free.
         */
        LineQuoteModel: {
            /** American */
            american: number;
            /** Book */
            book: string;
            /** Fetched At */
            fetched_at?: string | null;
            /** Implied Prob */
            implied_prob: number;
            /** Is Sharp Book */
            is_sharp_book: boolean;
            /** Line */
            line?: number | null;
            /** Line Type */
            line_type: string;
            /** Other American */
            other_american?: number | null;
        };
        /**
         * LinescoreModel
         * @description Response model for :class:`simulation.linescore.Linescore` (SIM-362).
         *
         *     The classic baseball linescore: the per-inning run grid plus each team's
         *     Runs / Hits / Errors totals.  ``innings`` is ordered 1..N (N >= 9 for extra
         *     innings).  ``away_by_inning`` / ``home_by_inning`` mirror the source's derived
         *     per-inning cell lists (``None`` == not played); ``n_innings`` mirrors the
         *     derived length.  numpy-free (plain ints / Optional[int]).
         */
        LinescoreModel: {
            /** Away By Inning */
            away_by_inning?: (number | null)[];
            /**
             * Away Errors
             * @default 0
             */
            away_errors: number;
            /**
             * Away Hits
             * @default 0
             */
            away_hits: number;
            /**
             * Away Runs
             * @default 0
             */
            away_runs: number;
            /** Home By Inning */
            home_by_inning?: (number | null)[];
            /**
             * Home Errors
             * @default 0
             */
            home_errors: number;
            /**
             * Home Hits
             * @default 0
             */
            home_hits: number;
            /**
             * Home Runs
             * @default 0
             */
            home_runs: number;
            /** Innings */
            innings?: components["schemas"]["InningLineModel"][];
            /**
             * N Innings
             * @default 0
             */
            n_innings: number;
        };
        /**
         * LiveGameStateResponse
         * @description SIM-386 response: live in-progress game state from ``sim.lineup_state``.
         *
         *     Fields are extracted from the ``game_state`` JSONB blob written by the live
         *     ingestion pipeline (:class:`~pipeline.live.live_ingestion_pipeline.GameStateBuilder`).
         *     All fields default to neutral / empty values so a partially-built game_state
         *     (e.g. a game that just went Live with no pitches yet) never breaks
         *     deserialization -- the frontend handles sparse state gracefully.
         *
         *     ``updated_at`` (ISO-8601 string) is the pipeline's last-write timestamp; the
         *     frontend can use it to detect staleness (> ~30s without an update may mean
         *     the pipeline lost the WS signal and is polling-fallback).
         */
        LiveGameStateResponse: {
            /** Away Bench */
            away_bench?: number[];
            /** Away Bullpen */
            away_bullpen?: number[];
            /** Away Lineup */
            away_lineup?: number[];
            /**
             * Away Score
             * @default 0
             */
            away_score: number;
            /**
             * Balls
             * @default 0
             */
            balls: number;
            /** Batting Team Id */
            batting_team_id?: number | null;
            /** Current Batter Id */
            current_batter_id?: number | null;
            /** Current Pitcher Id */
            current_pitcher_id?: number | null;
            /** Fielding Team Id */
            fielding_team_id?: number | null;
            /** Game Pk */
            game_pk: number;
            /**
             * Half
             * @default Top
             */
            half: string;
            /** Home Bench */
            home_bench?: number[];
            /** Home Bullpen */
            home_bullpen?: number[];
            /** Home Lineup */
            home_lineup?: number[];
            /**
             * Home Score
             * @default 0
             */
            home_score: number;
            /**
             * Inning
             * @default 1
             */
            inning: number;
            /** On 1B */
            on_1b?: number | null;
            /** On 2B */
            on_2b?: number | null;
            /** On 3B */
            on_3b?: number | null;
            /**
             * Outs
             * @default 0
             */
            outs: number;
            /** Session Id */
            session_id: string;
            /**
             * Strikes
             * @default 0
             */
            strikes: number;
            /** Updated At */
            updated_at?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
        };
        /**
         * MetricDeltaModel
         * @description Response model for :class:`simulation.snapshots.MetricDelta` (SIM-331).
         *
         *     A single baseline-vs-override metric.  ``delta`` (override - baseline) mirrors
         *     the source dataclass's derived property.
         */
        MetricDeltaModel: {
            /** Baseline */
            baseline: number;
            /** Delta */
            delta: number;
            /** Metric */
            metric: string;
            /** Override */
            override: number;
        };
        /**
         * OverrideDeltaModel
         * @description Response model for :class:`simulation.snapshots.OverrideDelta` (SIM-331).
         *
         *     The baseline-vs-override comparison: a ``{metric_name -> MetricDeltaModel}``
         *     map plus an optional free-text ``description`` of the roster change.
         */
        OverrideDeltaModel: {
            /** Description */
            description?: string | null;
            /** Metrics */
            metrics?: {
                [key: string]: components["schemas"]["MetricDeltaModel"];
            };
        };
        /**
         * PitcherDecisionsModel
         * @description Response model for :class:`simulation.pitcher_decisions.PitcherDecisions` (SIM-364).
         *
         *     The derived W/L/Save decision for one game.  All three pitcher ids are
         *     ``Optional[int]`` (``None`` when no decision can be made -- a tie, an
         *     empty/unfinished stream, or no save situation).  ``home_score`` / ``away_score``
         *     are the final committed scores for context.
         */
        PitcherDecisionsModel: {
            /**
             * Away Score
             * @default 0
             */
            away_score: number;
            /**
             * Home Score
             * @default 0
             */
            home_score: number;
            /** Losing Pitcher Id */
            losing_pitcher_id?: number | null;
            /** Save Pitcher Id */
            save_pitcher_id?: number | null;
            /** Winning Pitcher Id */
            winning_pitcher_id?: number | null;
        };
        /**
         * PlayByPlayEntryModel
         * @description Response model for :class:`simulation.snapshots.PlayByPlayEntry` (SIM-331).
         *
         *     One pitch in the /plays scroll.  ``at_bat`` groups pitches into a PA, ``pitch``
         *     is the 1-based pitch within the PA, ``sequence`` is the global pitch index;
         *     the PA's resolved event is carried on the terminal pitch (``is_pa_end``).
         */
        PlayByPlayEntryModel: {
            /** At Bat */
            at_bat: number;
            /** Canonical Event */
            canonical_event?: string | null;
            /** Event */
            event?: string | null;
            /** Exit Velo */
            exit_velo?: number | null;
            /** Is Contact */
            is_contact: boolean;
            /** Is Pa End */
            is_pa_end: boolean;
            /** Launch Angle */
            launch_angle?: number | null;
            /**
             * Outs Recorded
             * @default 0
             */
            outs_recorded: number;
            /** Pitch */
            pitch: number;
            /** Pitch Outcome */
            pitch_outcome: string;
            /**
             * Runs
             * @default 0
             */
            runs: number;
            /**
             * Runs Scored
             * @default 0
             */
            runs_scored: number;
            /** Sequence */
            sequence: number;
            /** Spray Angle */
            spray_angle?: number | null;
        };
        /**
         * PlayByPlayModel
         * @description Response model for :class:`simulation.snapshots.PlayByPlay` (SIM-331).
         *
         *     The GET /api/games/{game_pk}/plays collection -- pitch-level entries plus the
         *     source's derived counts (``n_pitches`` / ``n_plate_appearances``).
         */
        PlayByPlayModel: {
            /** Entries */
            entries?: components["schemas"]["PlayByPlayEntryModel"][];
            /**
             * N Pitches
             * @default 0
             */
            n_pitches: number;
            /**
             * N Plate Appearances
             * @default 0
             */
            n_plate_appearances: number;
            /** Page Limit */
            page_limit?: number | null;
            /** Page Offset */
            page_offset?: number | null;
            /** Returned Entries */
            returned_entries?: number | null;
            /** Total Entries */
            total_entries?: number | null;
        };
        /**
         * PlayerRefModel
         * @description Response model for :class:`simulation.snapshots.PlayerRef`.
         *
         *     A player reference: integer id + optional display label.
         */
        PlayerRefModel: {
            /** Label */
            label?: string | null;
            /** Player Id */
            player_id: number;
        };
        /**
         * PropEdgeResponse
         * @description SIM-390 response for GET /{game_pk}/props/{player_id}/{prop}.
         *
         *     The full integer-support PMF for one player's one prop over a Monte-Carlo
         *     run, enriched with optional over/under probabilities and an edge report.
         *
         *     When a ``line`` query param is supplied the ``p_over``, ``p_under``, and
         *     ``p_push`` fields are populated using the sportsbook convention
         *     (half-integer line: over + under == 1; integer line: a push mass is
         *     excluded from both).  When ``over_ml`` and ``under_ml`` are also supplied
         *     the ``edge_report`` is populated via
         *     :func:`betting.clv_engine.prop_edge_report`; the side evaluated is
         *     determined by the ``bet_side`` query param (``"over"`` or ``"under"``).
         *
         *     ``pmf`` is the ``{str(value) -> probability}`` map for direct consumer use
         *     (JSON object keys must be strings, so integer outcomes are stringified).
         */
        PropEdgeResponse: {
            edge_report?: components["schemas"]["EdgeReportModel"] | null;
            /** Line */
            line?: number | null;
            /** Mean */
            mean: number;
            /** Median */
            median: number;
            /** N */
            n: number;
            /** P Over */
            p_over?: number | null;
            /** P Push */
            p_push?: number | null;
            /** P Under */
            p_under?: number | null;
            /** Player Id */
            player_id: number;
            /** Pmf */
            pmf?: {
                [key: string]: number;
            };
            /** Probabilities */
            probabilities: number[];
            /** Prop */
            prop: string;
            /** Std */
            std: number;
            /** Support */
            support: number[];
        };
        /**
         * RosterOverride
         * @description The ``POST .../simulate/with_override`` request body (SIM-358 + SIM-388).
         *
         *     Every field is OPTIONAL; an unset field keeps the resolved (baseline) value.
         *     At least one field SHOULD be set for the override to differ from baseline,
         *     but an all-empty body is accepted (it yields an all-zero delta -- a valid,
         *     if uninteresting, comparison).
         *
         *       * ``home_lineup`` / ``away_lineup`` -- full 1..9 batting orders (player
         *         ids) to swap in for that side.  When set, REPLACES the entire lineup
         *         before any ``substitutions`` are applied.
         *       * ``substitutions`` -- SIM-388: a list of :class:`SubstitutionSlot`
         *         targeted single-player changes applied AFTER any full-lineup replacements.
         *         Use this to stage individual subs without knowing the full batting order.
         *         Left-to-right application; same-slot conflicts → last entry wins.
         *       * ``pitcher_id`` -- the pitcher to face the batters for the simulated half.
         *       * ``bat_hand`` -- the leadoff batter's hand override ('L'/'R'/'S'); the
         *         sampler pre-filter key.
         *       * ``description`` -- free text recorded on the returned OverrideDelta.
         */
        RosterOverride: {
            /** Away Lineup */
            away_lineup?: number[] | null;
            /** Bat Hand */
            bat_hand?: string | null;
            /** Description */
            description?: string | null;
            /** Home Lineup */
            home_lineup?: number[] | null;
            /** Pitcher Id */
            pitcher_id?: number | null;
            /** Substitutions */
            substitutions?: components["schemas"]["SubstitutionSlot"][] | null;
        };
        /**
         * SeasonCoverage
         * @description Per-season ingest coverage.
         */
        SeasonCoverage: {
            /** Games */
            games: number;
            /** Pitches */
            pitches: number;
            /** Season */
            season: number;
        };
        /**
         * SignalsResponse
         * @description The ``GET /api/betting/games/{game_pk}/signals`` envelope.
         *
         *     Carries the ranked (+EV, EV descending) :class:`BetSignalModel` list plus the
         *     run metadata, the gate config that produced them (min_edge / min_ev /
         *     kelly_fraction / max_stake_fraction), and the per-market ``odds_source`` flags.
         */
        SignalsResponse: {
            /** Base Seed */
            base_seed?: number | null;
            /** Config */
            config?: {
                [key: string]: number;
            };
            /** Game Pk */
            game_pk: number;
            /** N Iterations */
            n_iterations: number;
            /** Odds Source */
            odds_source?: {
                [key: string]: string;
            };
            /** Signals */
            signals?: components["schemas"]["BetSignalModel"][];
        };
        /**
         * SimilarityDistributionResponse
         * @description Top-level response for the histogram endpoint.
         */
        SimilarityDistributionResponse: {
            /** Bins */
            bins: components["schemas"]["_Bin"][];
            diagnostic: components["schemas"]["_Diagnostic"];
            /** Engine */
            engine: string;
            /** Engine Version */
            engine_version: string;
            /** Population Size */
            population_size: number;
            query: components["schemas"]["_Query"];
            score_summary: components["schemas"]["_ScoreSummary"];
            /** Top N */
            top_n: components["schemas"]["_Member"][];
        };
        /**
         * SimulateResponse
         * @description The ``GET /api/games/{game_pk}/simulate`` envelope.
         */
        SimulateResponse: {
            /** Base Seed */
            base_seed?: number | null;
            /**
             * From Cache
             * @default false
             */
            from_cache: boolean;
            /** Game Pk */
            game_pk: number;
            /** N Iterations */
            n_iterations: number;
            summary: components["schemas"]["GameSimSummaryModel"];
        };
        /**
         * StateAtPitchModel
         * @description Response model for :class:`simulation.snapshots.StateAtPitch` (SIM-331).
         *
         *     A point-in-time :class:`FieldSnapshotModel` tagged with the at-bat / pitch
         *     indices (and global sequence, if known).
         */
        StateAtPitchModel: {
            /** At Bat */
            at_bat: number;
            field: components["schemas"]["FieldSnapshotModel"];
            /** Pitch */
            pitch: number;
            /** Sequence */
            sequence?: number | null;
        };
        /**
         * SubstitutionSlot
         * @description A single targeted player substitution (SIM-388).
         *
         *     Replaces the player at a specific batting-order slot on one side of the
         *     lineup, without having to know or pass the other 8 slots.  One or more of
         *     these can appear in :attr:`RosterOverride.substitutions` to stage a
         *     multi-sub override queue.
         *
         *       * ``batting_order`` -- 1-indexed slot (1 = leadoff … 9 = ninth).
         *       * ``player_id``     -- the replacement player's MLB player ID.
         *       * ``side``          -- ``"home"`` or ``"away"``.
         *
         *     Multiple ``SubstitutionSlot`` items for the SAME (side, batting_order) in
         *     a single request are applied left-to-right, so the last one wins.
         */
        SubstitutionSlot: {
            /**
             * Batting Order
             * @description 1-indexed lineup slot (1–9)
             */
            batting_order: number;
            /**
             * Player Id
             * @description MLB player_id of the substitute
             */
            player_id: number;
            /**
             * Side
             * @description Which side's lineup to modify
             * @enum {string}
             */
            side: "home" | "away";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WithOverrideResponse
         * @description The ``POST .../simulate/with_override`` envelope (SIM-358).
         *
         *     Carries the BASELINE summary, the OVERRIDE summary (both run at the SAME
         *     base seed for an apples-to-apples comparison), and the OverrideDelta diff.
         */
        WithOverrideResponse: {
            /** Base Seed */
            base_seed?: number | null;
            baseline: components["schemas"]["GameSimSummaryModel"];
            delta: components["schemas"]["OverrideDeltaModel"];
            /** Game Pk */
            game_pk: number;
            /** N Iterations */
            n_iterations: number;
            override: components["schemas"]["GameSimSummaryModel"];
        };
        /** _Bin */
        _Bin: {
            /** Bin Index */
            bin_index: number;
            /** Count */
            count: number;
            /** Hi */
            hi: number;
            /** Lo */
            lo: number;
            /** Members */
            members: components["schemas"]["_Member"][];
            /** Preview */
            preview: components["schemas"]["_Member"][];
        };
        /** _Diagnostic */
        _Diagnostic: {
            /** Median Observed */
            median_observed: number;
            /** Median Target */
            median_target: number;
            /** Status */
            status: string;
        };
        /**
         * _Member
         * @description One pitcher's appearance in a bin / preview / top-N list.
         */
        _Member: {
            /** Arsenal Score */
            arsenal_score: number;
            /** Command Score */
            command_score: number;
            /** Full Name */
            full_name: string;
            /** P Throws */
            p_throws: string;
            /** Pitcher Id */
            pitcher_id: number;
            /** Sample Pitches */
            sample_pitches: number;
            /** Score */
            score: number;
            /** Season */
            season: number;
        };
        /** _Query */
        _Query: {
            /** Full Name */
            full_name: string;
            /** P Throws */
            p_throws: string;
            /** Pitcher Id */
            pitcher_id: number;
            /** Season */
            season: number;
        };
        /** _ScoreSummary */
        _ScoreSummary: {
            /** Max */
            max: number;
            /** Mean */
            mean: number;
            /** Median */
            median: number;
            /** Min */
            min: number;
            /** P25 */
            p25: number;
            /** P75 */
            p75: number;
            /** Std */
            std: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_game_clv_api_betting_games__game_pk__clv_get: {
        parameters: {
            query?: {
                /** @description moneyline | runline | total */
                market_type?: string;
                /** @description Restrict to one book (else all books) */
                book?: string | null;
            };
            header?: never;
            path: {
                game_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClvSnapshotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_edges_api_betting_games__game_pk__edges_get: {
        parameters: {
            query?: {
                /** @description Monte-Carlo iterations */
                n_iterations?: number;
                /** @description Reproducibility seed for the batch */
                base_seed?: number | null;
                /** @description Consult/populate the sim-result cache */
                use_cache?: boolean;
                /** @description Comma-separated subset of moneyline,total,runline (default all) */
                markets?: string | null;
                /** @description Injected home moneyline (American) */
                home_ml?: number | null;
                /** @description Injected away moneyline (American) */
                away_ml?: number | null;
                /** @description Injected total over price (American) */
                over_ml?: number | null;
                /** @description Injected total under price (American) */
                under_ml?: number | null;
                /** @description Injected total line */
                total_line?: number | null;
                /** @description Injected home run-line price (American) */
                home_rl_ml?: number | null;
                /** @description Injected away run-line price (American) */
                away_rl_ml?: number | null;
                /** @description Injected HOME run line (e.g. -1.5) */
                run_line?: number | null;
            };
            header?: never;
            path: {
                game_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_line_movement_api_betting_games__game_pk__line_movement_get: {
        parameters: {
            query?: {
                /** @description moneyline | runline | total */
                market_type?: string;
                /** @description Restrict to one book (else all books) */
                book?: string | null;
            };
            header?: never;
            path: {
                game_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineMovementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_signals_api_betting_games__game_pk__signals_get: {
        parameters: {
            query?: {
                /** @description Monte-Carlo iterations */
                n_iterations?: number;
                /** @description Reproducibility seed for the batch */
                base_seed?: number | null;
                /** @description Consult/populate the sim-result cache */
                use_cache?: boolean;
                /** @description Comma-separated subset of moneyline,total,runline (default all) */
                markets?: string | null;
                /** @description Edge noise floor (gate) */
                min_edge?: number;
                /** @description Minimum EV per unit (strict >) */
                min_ev?: number;
                /** @description Fractional-Kelly multiplier */
                kelly_fraction?: number;
                /** @description Hard cap on the stake fraction */
                max_stake_fraction?: number;
                /** @description Injected home moneyline (American) */
                home_ml?: number | null;
                /** @description Injected away moneyline (American) */
                away_ml?: number | null;
                /** @description Injected total over price (American) */
                over_ml?: number | null;
                /** @description Injected total under price (American) */
                under_ml?: number | null;
                /** @description Injected total line */
                total_line?: number | null;
                /** @description Injected home run-line price (American) */
                home_rl_ml?: number | null;
                /** @description Injected away run-line price (American) */
                away_rl_ml?: number | null;
                /** @description Injected HOME run line (e.g. -1.5) */
                run_line?: number | null;
            };
            header?: never;
            path: {
                game_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_data_freshness_api_data_freshness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataFreshnessResponse"];
                };
            };
        };
    };
    get_games_on_date_api_games__date__get: {
        parameters: {
            query?: {
                /** @description Consult/populate the listing cache */
                use_cache?: boolean;
            };
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamesOnDateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_boxscore_api_games__game_pk__boxscore_get: {
        parameters: {
            query?: {
                /** @description Monte-Carlo iterations */
                n_iterations?: number;
                /** @description Reproducibility seed for the batch */
                base_seed?: number | null;
            };
            header?: never;
            path: {
                game_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoxscoreCardModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_card_api_games__game_pk__card_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameCardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_decisions_api_games__game_pk__decisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PitcherDecisionsModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_linescore_api_games__game_pk__linescore_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinescoreModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_live_game_state_api_games__game_pk__live_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveGameStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_plays_api_games__game_pk__plays_get: {
        parameters: {
            query?: {
                /** @description Page size; omit to return all entries */
                limit?: number | null;
                /** @description 0-based offset of the entry slice */
                offset?: number;
            };
            header?: never;
            path: {
                game_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayByPlayModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_prop_edge_api_games__game_pk__props__player_id___prop__get: {
        parameters: {
            query?: {
                /** @description Monte-Carlo iterations */
                n_iterations?: number;
                /** @description Reproducibility seed for the batch */
                base_seed?: number | null;
                /** @description Prop line for over/under calculation */
                line?: number | null;
                /** @description American odds for the OVER side */
                over_ml?: number | null;
                /** @description American odds for the UNDER side */
                under_ml?: number | null;
                /** @description Side to compute edge for ('over' or 'under') */
                bet_side?: string;
            };
            header?: never;
            path: {
                game_pk: number;
                player_id: number;
                prop: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropEdgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_game_endpoint_api_games__game_pk__simulate_get: {
        parameters: {
            query?: {
                /** @description Monte-Carlo iterations */
                n_iterations?: number;
                /** @description Reproducibility seed for the whole batch */
                base_seed?: number | null;
                /** @description Consult/populate the sim-result cache */
                use_cache?: boolean;
            };
            header?: never;
            path: {
                game_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_with_override_endpoint_api_games__game_pk__simulate_with_override_post: {
        parameters: {
            query?: {
                /** @description Monte-Carlo iterations */
                n_iterations?: number;
                /** @description Shared seed for baseline + override */
                base_seed?: number | null;
                /** @description Consult/populate the sim-result cache */
                use_cache?: boolean;
            };
            header?: never;
            path: {
                game_pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RosterOverride"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithOverrideResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_state_at_pitch_api_games__game_pk__state__at_bat___pitch__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_pk: number;
                at_bat: number;
                pitch: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateAtPitchModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_status_card_api_games__game_pk__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameCardAggregateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_todays_odds_api_odds_today_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    get_game_odds_api_odds__game_pk__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pitcher_similarity_distribution_api_similarity_pitcher__pitcher_id___season__get: {
        parameters: {
            query?: {
                /** @description Histogram bin count */
                bins?: number;
                /** @description Top-N highlight band */
                top_n?: number;
            };
            header?: never;
            path: {
                pitcher_id: number;
                season: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarityDistributionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatusResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
